//
(princ "1:")(princ (cons 1 (cons (cons 2 (cons 3 '())) '())))
(terpri)
(princ "1:")(princ (list 1 (list 2 3)))
(terpri)
(princ "2:")(princ (cons 1 (cons (cons 2 '()) (cons 3 '()))))
(terpri)
(princ "2:")(princ (list 1 (list 2) 3))
(terpri)
(princ "3:")(princ (cons (cons (cons 1 (cons 2 (cons 3 '()))) '()) '()))
(terpri)
(princ "3:")(princ (list (list (list 1 2 3))))
(terpri)
(princ "4:")(princ (cons (cons 1 '()) (cons (cons 2 (cons (cons 3 '()) '())) '())))
(terpri)
(princ "4:")(princ (list (list 1) (list 2 (list 3))))
(terpri)
(princ "5:")(princ (cons (cons 1 '()) (cons (cons 2 (cons 3 '())) '())))
(terpri)
(princ "5:")(princ (list (list 1) (list 2 3)))
(terpri)
(princ "6:")(princ (cons (cons 1 (cons (cons 2 (cons (cons 3 '()) '())) '())) '()))
(terpri)
(princ "6:")(princ (list (list 1 (list 2 (list 3)))))
(terpri)
(princ "7:")(princ (cons (cons 1 (cons 2 (cons (cons (cons 3 '()) '()) '()))) '()))
(terpri)
(princ "7:")(princ (list (list 1 2 (list (list 3)))))
(terpri)
(princ "8:")(princ (cons (cons 1 (cons 2 '())) (cons 3 '())))
(terpri)
(princ "8:")(princ (list (list 1 2) 3))
(terpri)
(princ "9:")(princ (cons (cons (cons (cons 1 '()) '()) (cons 2 '())) (cons 3 '())))
(terpri)
(princ "9:")(princ (list (list (list (list 1)) 2) 3))
(terpri)
(princ "10:")(princ (cons 1 (cons (cons (cons 2 '()) '()) (cons (cons 3 '()) '()))))
(terpri)
(princ "10:")(princ (list 1 (list (list 2)) (list 3)))
(terpri)

(bye)
