//
(princ "1:")(princ (cons nil nil))
(terpri)
(princ "2:")(princ (list '(a b) 7 '(())))
(terpri)
(princ "3:")(princ (cons '(+ 1 2) '(+ 4 6)))
(terpri)
(princ "4:")(princ (append '(+ 1 2) '()))
(terpri)
(princ "5:")(princ (cons '(a (b c)) nil))
(terpri)
(princ "6:")(princ (append nil '(a b c)))
(terpri)
(princ "7:")(princ (list '(+ 1 2) '() '(+ 1)))
(terpri)
(princ "8:")(princ (append '(4 5 6) '()'(())))
(terpri)
(princ "9:")(princ (cons (+ 1 2) '(+ 4 6)))
(terpri)
(princ "10:")(princ (list '(+ 1 2) '()))
(terpri)

(bye)
